# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160102_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='roomID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='isInhabitable',
            field=models.BooleanField(default=True, verbose_name='Livable?'),
        ),
    ]
