# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20160102_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='House points')),
                ('isAlumni', models.BooleanField(default=False)),
                ('quarterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Quarter')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Room')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quarter_userstatus',
            name='quarterID',
        ),
        migrations.RemoveField(
            model_name='quarter_userstatus',
            name='userStatusID',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='roomID',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Quarter_UserStatus',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
