# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160102_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
