# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160102_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenduty',
            name='quarterID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Quarter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chore',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
