# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20160103_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_kitchenduty',
            name='kitchenDutyID',
        ),
        migrations.RemoveField(
            model_name='user_kitchenduty',
            name='userID',
        ),
        migrations.AddField(
            model_name='kitchenduty',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_KitchenDuty',
        ),
    ]
