# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160103_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore_day',
            name='choreID',
        ),
        migrations.RemoveField(
            model_name='chore_day',
            name='dayID',
        ),
        migrations.AddField(
            model_name='chore',
            name='daysDue',
            field=models.ManyToManyField(to='core.Day'),
        ),
        migrations.DeleteModel(
            name='Chore_Day',
        ),
    ]
