# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 00:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20160103_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bondNumber', models.IntegerField(null=True)),
                ('isAlumni', models.BooleanField(default=False)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Quarter_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='chore',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='daysDue',
        ),
        migrations.RemoveField(
            model_name='kitchenduty',
            name='quarterID',
        ),
        migrations.RemoveField(
            model_name='kitchenduty',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='user_quarter',
            name='isAlumni',
        ),
        migrations.RemoveField(
            model_name='user_quarter',
            name='roomID',
        ),
        migrations.RemoveField(
            model_name='user_quarter',
            name='userID',
        ),
        migrations.AddField(
            model_name='quarter',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2016, 4, 6, 0, 7, 28, 310106, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarter',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2016, 4, 6, 0, 7, 36, 688371, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_quarter',
            name='isLiveIn',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Chore',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='KitchenDuty',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='user_quarter_role',
            name='userQuarterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Quarter'),
        ),
        migrations.AddField(
            model_name='user_quarter',
            name='memberID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
            preserve_default=False,
        ),
    ]
