# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_quarter_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bondNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='season',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user_quarter',
            name='points',
            field=models.IntegerField(blank=True, default=0, verbose_name='House points'),
        ),
    ]
