# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160405_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Quarter',
            new_name='Member_Quarter',
        ),
        migrations.RenameModel(
            old_name='User_Quarter_Role',
            new_name='Member_Quarter_Role',
        ),
        migrations.AddField(
            model_name='quarter',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='spots',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='quarter_role',
            name='memberQuarterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member_Quarter'),
        ),
        migrations.AddField(
            model_name='quarter_role',
            name='roleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role'),
        ),
    ]
